"""Fleet health HTML report generator."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pytableau.fleet.scanner import WorkbookScan

_GRADE_COLORS = {
    "A": "#27ae60",
    "B": "#2ecc71",
    "C": "#f39c12",
    "D": "#e67e22",
    "F": "#e74c3c",
    "?": "#95a5a6",
}


class FleetReport:
    """Renders fleet scan results as HTML or a summary dict.

    Obtain via :meth:`~pytableau.fleet.scanner.FleetScanner.report`.
    """

    def __init__(self, scans: list[WorkbookScan]) -> None:
        self._scans = scans

    def summary(self) -> dict[str, Any]:
        """Return key fleet health metrics as a plain dict."""
        ok = [s for s in self._scans if s.status == "ok"]
        grades: dict[str, int] = {}
        for s in ok:
            g = s.complexity_grade or "?"
            grades[g] = grades.get(g, 0) + 1
        return {
            "total": len(self._scans),
            "ok": len(ok),
            "errors": len(self._scans) - len(ok),
            "complexity_distribution": grades,
            "workbooks_with_live_connections": sum(1 for s in ok if s.has_live_connections),
            "workbooks_with_deprecated_functions": sum(1 for s in ok if s.has_deprecated_functions),
        }

    def to_dict(self) -> dict[str, Any]:
        """Return full scan data as a JSON-serialisable dict."""
        return {
            "summary": self.summary(),
            "workbooks": [s.to_dict() for s in self._scans],
        }

    def to_html(self, path: str | Path | None = None) -> str:
        """Render a standalone HTML fleet health dashboard.

        If *path* is given, write to disk.  Always returns the HTML string.
        """
        ok = [s for s in self._scans if s.status == "ok"]
        errors = [s for s in self._scans if s.status == "error"]
        summary = self.summary()
        grades = summary["complexity_distribution"]

        grade_bars = "".join(
            f'<div class="grade-bar" style="border-left:6px solid {_GRADE_COLORS.get(g, "#ccc")}">'
            f'<span class="grade-label">{g}</span>'
            f'<span class="grade-count">{count}</span></div>'
            for g, count in sorted(grades.items())
        )

        rows = ""
        for s in self._scans:
            if s.status == "error":
                rows += (
                    f"<tr class='error'><td>{s.path.name}</td>"
                    f"<td colspan='7' class='err-msg'>ERROR: {s.error or ''}</td></tr>\n"
                )
            else:
                color = _GRADE_COLORS.get(s.complexity_grade or "?", "#ccc")
                live = "yes" if s.has_live_connections else ""
                depr = "yes" if s.has_deprecated_functions else ""
                rows += (
                    f"<tr>"
                    f"<td>{s.path.name}</td>"
                    f"<td>{s.version or '?'}</td>"
                    f"<td style='color:{color};font-weight:bold'>{s.complexity_grade or '?'} ({s.complexity_score})</td>"
                    f"<td>{s.datasource_count}</td>"
                    f"<td>{s.worksheet_count}</td>"
                    f"<td>{s.calc_field_count}/{s.field_count}</td>"
                    f"<td class='flag'>{live}</td>"
                    f"<td class='flag'>{depr}</td>"
                    f"</tr>\n"
                )

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>pytableau Fleet Health Report</title>
<style>
body{{font-family:'Segoe UI',Arial,sans-serif;margin:0;padding:24px;background:#f8f9fa;color:#222}}
h1{{font-size:1.6rem;margin-bottom:4px}}
.subtitle{{color:#666;margin-bottom:24px}}
.cards{{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:24px}}
.card{{background:#fff;border-radius:8px;padding:16px 24px;box-shadow:0 1px 4px rgba(0,0,0,.1);min-width:120px}}
.card .num{{font-size:2rem;font-weight:700}}
.card .label{{color:#666;font-size:.85rem}}
.grades{{background:#fff;border-radius:8px;padding:16px 24px;box-shadow:0 1px 4px rgba(0,0,0,.1);margin-bottom:24px}}
.grades h2{{font-size:1rem;margin-top:0}}
.grade-bar{{display:flex;align-items:center;gap:12px;padding:4px 0;border-left-width:6px;border-left-style:solid;padding-left:8px;margin-bottom:4px}}
.grade-label{{font-weight:700;width:20px}}
.grade-count{{color:#444}}
table{{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.1)}}
th{{background:#343a40;color:#fff;padding:10px 12px;text-align:left;font-size:.85rem}}
td{{padding:8px 12px;border-bottom:1px solid #eee;font-size:.85rem}}
tr:last-child td{{border-bottom:none}}
tr.error{{background:#fff5f5}}
.err-msg{{color:#c0392b;font-size:.8rem}}
.flag{{text-align:center;color:#e67e22}}
</style>
</head>
<body>
<h1>Fleet Health Report</h1>
<p class="subtitle">Generated by pytableau &mdash; {len(self._scans)} workbooks scanned</p>
<div class="cards">
  <div class="card"><div class="num">{len(self._scans)}</div><div class="label">Total</div></div>
  <div class="card"><div class="num">{len(ok)}</div><div class="label">OK</div></div>
  <div class="card" style="border-top:3px solid #e74c3c"><div class="num">{len(errors)}</div><div class="label">Errors</div></div>
  <div class="card"><div class="num">{summary["workbooks_with_live_connections"]}</div><div class="label">Live Connections</div></div>
  <div class="card"><div class="num">{summary["workbooks_with_deprecated_functions"]}</div><div class="label">Deprecated Fns</div></div>
</div>
<div class="grades"><h2>Complexity Distribution</h2>{grade_bars}</div>
<table>
<thead><tr>
  <th>Workbook</th><th>Version</th><th>Complexity</th>
  <th>Datasources</th><th>Worksheets</th><th>Calc/Total Fields</th>
  <th>Live</th><th>Deprecated</th>
</tr></thead>
<tbody>{rows}</tbody>
</table>
</body>
</html>"""

        if path is not None:
            Path(path).write_text(html, encoding="utf-8")
        return html
